### PR TITLE
Fix compilation errors.

### PR DESCRIPTION
**Pull request by sunnyden**
This fixes the error when compiling module libOmxVenc_32
When I try to build the cm14.1 using this branch of the kernel, the complier reports that identifiers like "MSM_VIDC_TRANSFER_LINEAR" etc were missing. By adding those declaration would fix this compilation error

### CODE REVIEW

**Comment by h2o64** [comment]
I think a commit history would be much more appreciated

**Comment by sunnyden** [comment]
Well, It seems that a lot of definitions were missed in this branch, not only this file ...

**Comment by h2o64** [comment]
Yeah I need to upgrade vidc to latest UM too it seems

**Comment by bgcngm** [comment]
This will be fixed with proper cherry-picks.

**Pull request closed without merging**
